/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import javax.swing.*;
import java.sql.*;
import java.text.*;
import java.util.*;
import database.DBManager;

/**
 *
 * @author dulsh
 */
public class AddAssistantLecturer extends javax.swing.JFrame {

    private String Id;

    public AddAssistantLecturer(String Id) {
        initComponents();
        this.Id = Id;
        setTitle("Add Assistant Lecturer");
        setResizable(false);
        setLocationRelativeTo(null);
        loadLecturersIntoComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clearFormbtn = new javax.swing.JButton();
        AddLecturerbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NewAssistantLecturerName = new javax.swing.JTextField();
        NewLecturerEmail = new javax.swing.JTextField();
        NewAssistantLecturerPassword = new javax.swing.JTextField();
        NewAssistantLecturerAssignedLecturerjComboBox = new javax.swing.JComboBox<>();
        NewAssistantLecturerDepartmentjComboBox = new javax.swing.JComboBox<>();
        AddAssistantLecturerbtn = new javax.swing.JButton();
        clearFormbtn1 = new javax.swing.JButton();
        topdesign = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        headerText = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        homebtn = new javax.swing.JButton();

        clearFormbtn.setBackground(new java.awt.Color(102, 102, 255));
        clearFormbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearFormbtn.setForeground(new java.awt.Color(255, 255, 255));
        clearFormbtn.setText("Clear Form");
        clearFormbtn.setBorder(new javax.swing.border.MatteBorder(null));
        clearFormbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFormbtnActionPerformed(evt);
            }
        });

        AddLecturerbtn.setBackground(new java.awt.Color(102, 102, 255));
        AddLecturerbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddLecturerbtn.setForeground(new java.awt.Color(255, 255, 255));
        AddLecturerbtn.setText("Add Lecturer");
        AddLecturerbtn.setBorder(new javax.swing.border.MatteBorder(null));
        AddLecturerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLecturerbtnActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(234, 234, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Email :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Assigned Lecturer :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Department :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Password :");

        NewAssistantLecturerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewAssistantLecturerNameActionPerformed(evt);
            }
        });

        NewAssistantLecturerPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewAssistantLecturerPasswordActionPerformed(evt);
            }
        });

        NewAssistantLecturerAssignedLecturerjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewAssistantLecturerAssignedLecturerjComboBoxActionPerformed(evt);
            }
        });

        NewAssistantLecturerDepartmentjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science", "Computer Engineering", "Computational Mathematics", "Information Technology" }));

        AddAssistantLecturerbtn.setBackground(new java.awt.Color(102, 102, 255));
        AddAssistantLecturerbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddAssistantLecturerbtn.setForeground(new java.awt.Color(255, 255, 255));
        AddAssistantLecturerbtn.setText("Add Assistant Lecturer");
        AddAssistantLecturerbtn.setBorder(new javax.swing.border.MatteBorder(null));
        AddAssistantLecturerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAssistantLecturerbtnActionPerformed(evt);
            }
        });

        clearFormbtn1.setBackground(new java.awt.Color(102, 102, 255));
        clearFormbtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearFormbtn1.setForeground(new java.awt.Color(255, 255, 255));
        clearFormbtn1.setText("Clear Form");
        clearFormbtn1.setBorder(new javax.swing.border.MatteBorder(null));
        clearFormbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFormbtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NewAssistantLecturerPassword)
                                    .addComponent(NewAssistantLecturerAssignedLecturerjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(NewAssistantLecturerDepartmentjComboBox, 0, 806, Short.MAX_VALUE)
                                        .addGap(2, 2, 2))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(94, 94, 94)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NewLecturerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NewAssistantLecturerName, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(AddAssistantLecturerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(clearFormbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NewAssistantLecturerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(NewLecturerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(NewAssistantLecturerDepartmentjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NewAssistantLecturerAssignedLecturerjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewAssistantLecturerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddAssistantLecturerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearFormbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        topdesign.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout topdesignLayout = new javax.swing.GroupLayout(topdesign);
        topdesign.setLayout(topdesignLayout);
        topdesignLayout.setHorizontalGroup(
            topdesignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        topdesignLayout.setVerticalGroup(
            topdesignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Add New Assistant Lecturer");

        headerText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        headerText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo - icon.png"))); // NOI18N
        headerText.setText("   General Sir John Kotelawala Defence University (KDU)-Ratmalana");

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        homebtn.setBackground(new java.awt.Color(102, 102, 255));
        homebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        homebtn.setForeground(new java.awt.Color(255, 255, 255));
        homebtn.setText("Home");
        homebtn.setBorder(new javax.swing.border.MatteBorder(null));
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addComponent(topdesign, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(headerText, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(414, 414, 414))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(topdesign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerText, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearFormbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFormbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearFormbtnActionPerformed

    private void AddLecturerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLecturerbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddLecturerbtnActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        ManagementDashboard dashboard = new ManagementDashboard(Id);
        dashboard.setVisible(true);
        dashboard.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_homebtnActionPerformed

    private void clearFormbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFormbtn1ActionPerformed
        NewAssistantLecturerName.setText("");
        NewLecturerEmail.setText("");
        NewAssistantLecturerPassword.setText("");
        NewAssistantLecturerAssignedLecturerjComboBox.setSelectedIndex(0);
        NewAssistantLecturerDepartmentjComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_clearFormbtn1ActionPerformed

    private void AddAssistantLecturerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAssistantLecturerbtnActionPerformed
        String name = NewAssistantLecturerName.getText();
        String email = NewLecturerEmail.getText();
        String password = NewAssistantLecturerPassword.getText();
        String assignedLecturer = (String) NewAssistantLecturerAssignedLecturerjComboBox.getSelectedItem();
        String department = (String) NewAssistantLecturerDepartmentjComboBox.getSelectedItem();

        if (name.isEmpty() || email.isEmpty() || password.isEmpty() || assignedLecturer == null || department == null) {
            JOptionPane.showMessageDialog(this, "Please fill all the required fields.");
            return;
        }

        try {
            Connection conn = DBManager.getConnection();

            String getLecturerIdQuery = "SELECT Id FROM Lecturer WHERE Name = ?";
            PreparedStatement lecturerStmt = conn.prepareStatement(getLecturerIdQuery);
            lecturerStmt.setString(1, assignedLecturer);
            ResultSet lecturerResult = lecturerStmt.executeQuery();

            int lecturerId = -1;
            if (lecturerResult.next()) {
                lecturerId = lecturerResult.getInt("Id");
            } else {
                JOptionPane.showMessageDialog(this, "Assigned Lecturer not found.");
                return;
            }

            String getDepartmentIdQuery = "SELECT Id FROM Academic_Department WHERE Name = ?";
            PreparedStatement departmentStmt = conn.prepareStatement(getDepartmentIdQuery);
            departmentStmt.setString(1, department);
            ResultSet departmentResult = departmentStmt.executeQuery();

            int departmentId = -1;
            if (departmentResult.next()) {
                departmentId = departmentResult.getInt("Id");
            } else {
                JOptionPane.showMessageDialog(this, "Department not found.");
                return;
            }

            String sql = "INSERT INTO Lecturer_Assistant (Name, Email, Lecturer_Id, Department_Id) VALUES (?, ?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);

            pstmt.setString(1, name);
            pstmt.setString(2, email);
            pstmt.setInt(3, lecturerId);
            pstmt.setInt(4, departmentId);

            int rows = pstmt.executeUpdate();

            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Assistant Lecturer added successfully!");
                clearFormbtn1ActionPerformed(evt);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add Assistant Lecturer.");
            }

            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_AddAssistantLecturerbtnActionPerformed

    private void NewAssistantLecturerPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewAssistantLecturerPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewAssistantLecturerPasswordActionPerformed

    private void NewAssistantLecturerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewAssistantLecturerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewAssistantLecturerNameActionPerformed

    private void NewAssistantLecturerAssignedLecturerjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewAssistantLecturerAssignedLecturerjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewAssistantLecturerAssignedLecturerjComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAssistantLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAssistantLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAssistantLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAssistantLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAssistantLecturer("1234").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAssistantLecturerbtn;
    private javax.swing.JButton AddLecturerbtn;
    private javax.swing.JComboBox<String> NewAssistantLecturerAssignedLecturerjComboBox;
    private javax.swing.JComboBox<String> NewAssistantLecturerDepartmentjComboBox;
    private javax.swing.JTextField NewAssistantLecturerName;
    private javax.swing.JTextField NewAssistantLecturerPassword;
    private javax.swing.JTextField NewLecturerEmail;
    private javax.swing.JButton clearFormbtn;
    private javax.swing.JButton clearFormbtn1;
    private javax.swing.JLabel headerText;
    private javax.swing.JButton homebtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel topdesign;
    // End of variables declaration//GEN-END:variables

private void loadLecturersIntoComboBox() {
    try {
        Connection conn = DBManager.getConnection();
        String sql = "SELECT Name FROM Lecturer";
        PreparedStatement stmt = conn.prepareStatement(sql);
        ResultSet rs = stmt.executeQuery();

        NewAssistantLecturerAssignedLecturerjComboBox.removeAllItems(); // clear existing items

        while (rs.next()) {
            String lecturerName = rs.getString("Name");
            NewAssistantLecturerAssignedLecturerjComboBox.addItem(lecturerName);
        }

        rs.close();
        stmt.close();
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading lecturers: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}

}
