/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author dulsh
 */
import database.DBManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import java.sql.SQLException;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

public class LecturerDashboard extends javax.swing.JFrame {

    public LecturerDashboard(String Id) {
        initComponents();
        this.Id = Id;
        setTitle("Lecturer Dashboard");
        setResizable(false);
        loadLecturerProfile(Id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcometext = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        headerText = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        assignedSections = new javax.swing.JButton();
        myModules = new javax.swing.JButton();
        lecturerDetailsPanel = new javax.swing.JPanel();
        jLabelFullName = new javax.swing.JLabel();
        jLabelGender = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelDepartment = new javax.swing.JLabel();
        jLabelDegrees = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        degrees = new javax.swing.JTextField();
        department = new javax.swing.JTextField();
        jLabelLecturerID = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        topdesign = new javax.swing.JPanel();
        EditLecturerProfile = new javax.swing.JButton();
        manageGrades1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        welcometext.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        welcometext.setText("Welcome Back!");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(234, 234, 255));
        Header.setFocusTraversalPolicyProvider(true);
        Header.setInheritsPopupMenu(true);

        headerText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        headerText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo - icon.png"))); // NOI18N
        headerText.setText("   General Sir John Kotelawala Defence University (KDU)-Ratmalana");

        logout.setBackground(new java.awt.Color(255, 51, 51));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        assignedSections.setBackground(new java.awt.Color(106, 101, 255));
        assignedSections.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        assignedSections.setForeground(new java.awt.Color(255, 255, 255));
        assignedSections.setText("Assigned Sections");
        assignedSections.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        assignedSections.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assignedSectionsMouseClicked(evt);
            }
        });
        assignedSections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignedSectionsActionPerformed(evt);
            }
        });

        myModules.setBackground(new java.awt.Color(106, 101, 255));
        myModules.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        myModules.setForeground(new java.awt.Color(255, 255, 255));
        myModules.setText("My Modules");
        myModules.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        myModules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myModulesMouseClicked(evt);
            }
        });
        myModules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myModulesActionPerformed(evt);
            }
        });

        lecturerDetailsPanel.setBackground(new java.awt.Color(215, 215, 252));

        jLabelFullName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelFullName.setText("FullName :");

        jLabelGender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelGender.setText("Gender :");

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEmail.setText("Email :");

        jLabelDepartment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDepartment.setText("Department :");

        jLabelDegrees.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDegrees.setText("Degrees  :");

        name.setEditable(false);
        name.setBackground(new java.awt.Color(215, 215, 252));
        name.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        name.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        gender.setEditable(false);
        gender.setBackground(new java.awt.Color(215, 215, 252));
        gender.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        gender.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });

        email.setEditable(false);
        email.setBackground(new java.awt.Color(215, 215, 252));
        email.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        degrees.setEditable(false);
        degrees.setBackground(new java.awt.Color(215, 215, 252));
        degrees.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        degrees.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        degrees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreesActionPerformed(evt);
            }
        });

        department.setEditable(false);
        department.setBackground(new java.awt.Color(215, 215, 252));
        department.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        department.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });

        jLabelLecturerID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelLecturerID.setText("Lecturer ID :");

        id.setEditable(false);
        id.setBackground(new java.awt.Color(215, 215, 252));
        id.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        id.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lecturerDetailsPanelLayout = new javax.swing.GroupLayout(lecturerDetailsPanel);
        lecturerDetailsPanel.setLayout(lecturerDetailsPanelLayout);
        lecturerDetailsPanelLayout.setHorizontalGroup(
            lecturerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lecturerDetailsPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(lecturerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lecturerDetailsPanelLayout.createSequentialGroup()
                        .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email))
                    .addGroup(lecturerDetailsPanelLayout.createSequentialGroup()
                        .addComponent(jLabelLecturerID, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(lecturerDetailsPanelLayout.createSequentialGroup()
                        .addGroup(lecturerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lecturerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gender)
                            .addComponent(name)))
                    .addGroup(lecturerDetailsPanelLayout.createSequentialGroup()
                        .addGroup(lecturerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelDegrees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(lecturerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(degrees)
                            .addComponent(department))))
                .addContainerGap())
        );
        lecturerDetailsPanelLayout.setVerticalGroup(
            lecturerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lecturerDetailsPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(lecturerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLecturerID)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lecturerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFullName)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lecturerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGender)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lecturerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lecturerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDepartment)
                    .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lecturerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDegrees)
                    .addComponent(degrees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Lecturer Profile");

        topdesign.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout topdesignLayout = new javax.swing.GroupLayout(topdesign);
        topdesign.setLayout(topdesignLayout);
        topdesignLayout.setHorizontalGroup(
            topdesignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        topdesignLayout.setVerticalGroup(
            topdesignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        EditLecturerProfile.setBackground(new java.awt.Color(106, 101, 255));
        EditLecturerProfile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditLecturerProfile.setForeground(new java.awt.Color(255, 255, 255));
        EditLecturerProfile.setText("Edit Profile");
        EditLecturerProfile.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        EditLecturerProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditLecturerProfileMouseClicked(evt);
            }
        });
        EditLecturerProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditLecturerProfileActionPerformed(evt);
            }
        });

        manageGrades1.setBackground(new java.awt.Color(106, 101, 255));
        manageGrades1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        manageGrades1.setForeground(new java.awt.Color(255, 255, 255));
        manageGrades1.setText("Manage Grades");
        manageGrades1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        manageGrades1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageGrades1MouseClicked(evt);
            }
        });
        manageGrades1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageGrades1ActionPerformed(evt);
            }
        });

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel2.setText("Welcome Back!");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topdesign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(HeaderLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(myModules, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(assignedSections, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EditLecturerProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(manageGrades1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(lecturerDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 27, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(headerText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15))))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(topdesign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerText, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(EditLecturerProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(myModules, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(assignedSections, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(manageGrades1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lecturerDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jToggleButton1.setText("jToggleButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String Id;

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int response = JOptionPane.showConfirmDialog(
                this,
                "you sure want to logout?",
                "Confirm Logout",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (response == JOptionPane.YES_OPTION) {
            LoginInterface login = new LoginInterface();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void assignedSectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignedSectionsActionPerformed
        String lecturerId = Id;
        AssignedSectionsFrame assignedSectionsFrame = new AssignedSectionsFrame(lecturerId);
        assignedSectionsFrame.setLocationRelativeTo(null);
        assignedSectionsFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_assignedSectionsActionPerformed

    private void myModulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myModulesActionPerformed
        LecModulesFrame modulesFrame = new LecModulesFrame(Id);
        modulesFrame.setLocationRelativeTo(null);
        modulesFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_myModulesActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseClicked

    private void assignedSectionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignedSectionsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_assignedSectionsMouseClicked

    private void myModulesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myModulesMouseClicked

    }//GEN-LAST:event_myModulesMouseClicked

    private void EditLecturerProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditLecturerProfileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EditLecturerProfileMouseClicked

    private void EditLecturerProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditLecturerProfileActionPerformed
        String lecturerId = Id;
        EditLecturerProfile editProfileFrame = new EditLecturerProfile(lecturerId);
        editProfileFrame.setLocationRelativeTo(null);
        editProfileFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EditLecturerProfileActionPerformed

    private void manageGrades1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageGrades1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_manageGrades1MouseClicked

    private void manageGrades1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageGrades1ActionPerformed
        ManageGradesPanel gradesPanel = new ManageGradesPanel(Id);
        gradesPanel.setLocationRelativeTo(null);
        gradesPanel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageGrades1ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentActionPerformed

    private void degreesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degreesActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecturerDashboard("LECTURER123").setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditLecturerProfile;
    private javax.swing.JPanel Header;
    private javax.swing.JButton assignedSections;
    private javax.swing.JTextField degrees;
    private javax.swing.JTextField department;
    private javax.swing.JTextField email;
    private javax.swing.JTextField gender;
    private javax.swing.JLabel headerText;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDegrees;
    private javax.swing.JLabel jLabelDepartment;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFullName;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelLecturerID;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel lecturerDetailsPanel;
    private javax.swing.JButton logout;
    private javax.swing.JButton manageGrades1;
    private javax.swing.JButton myModules;
    private javax.swing.JTextField name;
    private javax.swing.JPanel topdesign;
    private javax.swing.JLabel welcometext;
    // End of variables declaration//GEN-END:variables

    private void loadLecturerProfile(String Id) {
        try {
            Connection conn = DBManager.getConnection();
            String query = "SELECT l.Id, l.Name, l.Gender, l.Email, l.Degrees, ad.Name AS DepartmentName "
                    + "FROM Lecturer l "
                    + "JOIN Academic_Department ad ON l.Department_Id = ad.Id "
                    + "WHERE l.Id = ?";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, Id);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                id.setText(rs.getString("Id"));
                name.setText(rs.getString("Name"));
                gender.setText(rs.getString("Gender"));
                email.setText(rs.getString("Email"));
                degrees.setText(rs.getString("Degrees"));
                department.setText(rs.getString("DepartmentName"));
            } else {
                JOptionPane.showMessageDialog(this, "Lecturer not found!");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading lecturer profile: " + e.getMessage());
            e.printStackTrace();
        }
    }

}
