/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author dulsh
 */
import database.DBManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class ManagementDashboard extends javax.swing.JFrame {

    private String Id;

    public ManagementDashboard(String Id) {
        setTitle("Management Dashboard");
        setResizable(false);
        setLocationRelativeTo(null);
        initComponents();
        this.Id = Id;
        loadManagementProfile(Id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        View_Departments = new javax.swing.JButton();
        Add_New_Students = new javax.swing.JButton();
        Manage_Lecturers = new javax.swing.JButton();
        manage_Students = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jobRole = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        department = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Add_New_Assistant_Lecturers = new javax.swing.JButton();
        Add_New_Management_Roles = new javax.swing.JButton();
        logout1 = new javax.swing.JButton();
        Manage_Courses = new javax.swing.JButton();
        Add_New_Lecturer = new javax.swing.JButton();
        Manage_Assistant_Lecturers = new javax.swing.JButton();
        headerText = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Manage_Management_Roles = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(234, 234, 255));
        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.setInheritsPopupMenu(true);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel2.setText("Welcome Back!");

        View_Departments.setBackground(new java.awt.Color(106, 101, 255));
        View_Departments.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        View_Departments.setForeground(new java.awt.Color(255, 255, 255));
        View_Departments.setText("Manage Departments");
        View_Departments.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        View_Departments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                View_DepartmentsMouseClicked(evt);
            }
        });
        View_Departments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_DepartmentsActionPerformed(evt);
            }
        });

        Add_New_Students.setBackground(new java.awt.Color(106, 101, 255));
        Add_New_Students.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Add_New_Students.setForeground(new java.awt.Color(255, 255, 255));
        Add_New_Students.setText("Add New Students");
        Add_New_Students.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Add_New_Students.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_New_StudentsMouseClicked(evt);
            }
        });
        Add_New_Students.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_New_StudentsActionPerformed(evt);
            }
        });

        Manage_Lecturers.setBackground(new java.awt.Color(106, 101, 255));
        Manage_Lecturers.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Manage_Lecturers.setForeground(new java.awt.Color(255, 255, 255));
        Manage_Lecturers.setText("Manage Lecturers");
        Manage_Lecturers.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Manage_Lecturers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Manage_LecturersMouseClicked(evt);
            }
        });
        Manage_Lecturers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_LecturersActionPerformed(evt);
            }
        });

        manage_Students.setBackground(new java.awt.Color(106, 101, 255));
        manage_Students.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manage_Students.setForeground(new java.awt.Color(255, 255, 255));
        manage_Students.setText("Manage Students");
        manage_Students.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        manage_Students.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manage_StudentsMouseClicked(evt);
            }
        });
        manage_Students.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_StudentsActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(215, 215, 252));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("FullName :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Job Role :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Email :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Department :");

        name.setEditable(false);
        name.setBackground(new java.awt.Color(215, 215, 252));
        name.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        name.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        jobRole.setEditable(false);
        jobRole.setBackground(new java.awt.Color(215, 215, 252));
        jobRole.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jobRole.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jobRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobRoleActionPerformed(evt);
            }
        });

        email.setEditable(false);
        email.setBackground(new java.awt.Color(215, 215, 252));
        email.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        department.setEditable(false);
        department.setBackground(new java.awt.Color(215, 215, 252));
        department.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        department.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Employee ID :");

        id.setEditable(false);
        id.setBackground(new java.awt.Color(215, 215, 252));
        id.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        id.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(54, 54, 54)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(name)
                                .addComponent(jobRole)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jobRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("My Profile");

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        Add_New_Assistant_Lecturers.setBackground(new java.awt.Color(106, 101, 255));
        Add_New_Assistant_Lecturers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Add_New_Assistant_Lecturers.setForeground(new java.awt.Color(255, 255, 255));
        Add_New_Assistant_Lecturers.setText("Add New Assistant Lecturers");
        Add_New_Assistant_Lecturers.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Add_New_Assistant_Lecturers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_New_Assistant_LecturersMouseClicked(evt);
            }
        });
        Add_New_Assistant_Lecturers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_New_Assistant_LecturersActionPerformed(evt);
            }
        });

        Add_New_Management_Roles.setBackground(new java.awt.Color(106, 101, 255));
        Add_New_Management_Roles.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Add_New_Management_Roles.setForeground(new java.awt.Color(255, 255, 255));
        Add_New_Management_Roles.setText("Add New Management Roles");
        Add_New_Management_Roles.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Add_New_Management_Roles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_New_Management_RolesMouseClicked(evt);
            }
        });
        Add_New_Management_Roles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_New_Management_RolesActionPerformed(evt);
            }
        });

        logout1.setBackground(new java.awt.Color(255, 51, 51));
        logout1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logout1.setForeground(new java.awt.Color(255, 255, 255));
        logout1.setText("Logout");
        logout1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        logout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout1MouseClicked(evt);
            }
        });
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout1ActionPerformed(evt);
            }
        });

        Manage_Courses.setBackground(new java.awt.Color(106, 101, 255));
        Manage_Courses.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Manage_Courses.setForeground(new java.awt.Color(255, 255, 255));
        Manage_Courses.setText("Manage Courses");
        Manage_Courses.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Manage_Courses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Manage_CoursesMouseClicked(evt);
            }
        });
        Manage_Courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_CoursesActionPerformed(evt);
            }
        });

        Add_New_Lecturer.setBackground(new java.awt.Color(106, 101, 255));
        Add_New_Lecturer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Add_New_Lecturer.setForeground(new java.awt.Color(255, 255, 255));
        Add_New_Lecturer.setText("Add New Lecturer");
        Add_New_Lecturer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Add_New_Lecturer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_New_LecturerMouseClicked(evt);
            }
        });
        Add_New_Lecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_New_LecturerActionPerformed(evt);
            }
        });

        Manage_Assistant_Lecturers.setBackground(new java.awt.Color(106, 101, 255));
        Manage_Assistant_Lecturers.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Manage_Assistant_Lecturers.setForeground(new java.awt.Color(255, 255, 255));
        Manage_Assistant_Lecturers.setText("Manage Assistant Lecturers");
        Manage_Assistant_Lecturers.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Manage_Assistant_Lecturers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Manage_Assistant_LecturersMouseClicked(evt);
            }
        });
        Manage_Assistant_Lecturers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_Assistant_LecturersActionPerformed(evt);
            }
        });

        headerText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        headerText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo - icon.png"))); // NOI18N
        headerText.setText("   General Sir John Kotelawala Defence University (KDU)-Ratmalana");

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Manage_Management_Roles.setBackground(new java.awt.Color(106, 101, 255));
        Manage_Management_Roles.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Manage_Management_Roles.setForeground(new java.awt.Color(255, 255, 255));
        Manage_Management_Roles.setText("Manage Management Roles");
        Manage_Management_Roles.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Manage_Management_Roles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Manage_Management_RolesMouseClicked(evt);
            }
        });
        Manage_Management_Roles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_Management_RolesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manage_Students, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Manage_Lecturers, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_New_Students, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_New_Lecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(View_Departments, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add_New_Management_Roles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Manage_Courses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Manage_Management_Roles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_New_Assistant_Lecturers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Manage_Assistant_Lecturers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(headerText, javax.swing.GroupLayout.PREFERRED_SIZE, 944, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(headerText, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(manage_Students, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(Add_New_Students, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(Manage_Lecturers, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(Add_New_Lecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(Manage_Assistant_Lecturers, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(Add_New_Assistant_Lecturers, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(Manage_Management_Roles, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(Add_New_Management_Roles, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Manage_Courses, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(View_Departments, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jToggleButton1.setText("jToggleButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Manage_Assistant_LecturersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_Assistant_LecturersActionPerformed
        ManageAssistantLecturers manageAssistantLecturers = new ManageAssistantLecturers(Id);
        manageAssistantLecturers.setLocationRelativeTo(null);
        manageAssistantLecturers.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Manage_Assistant_LecturersActionPerformed

    private void Manage_Assistant_LecturersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Manage_Assistant_LecturersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Manage_Assistant_LecturersMouseClicked

    private void Add_New_LecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_New_LecturerActionPerformed
        AddLecturer addLecturer = new AddLecturer(Id);
        addLecturer.setLocationRelativeTo(null);
        addLecturer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Add_New_LecturerActionPerformed

    private void Add_New_LecturerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_New_LecturerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_New_LecturerMouseClicked

    private void Manage_CoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_CoursesActionPerformed
        ManageCourses manageCourses = new ManageCourses(Id);
        manageCourses.setLocationRelativeTo(null);
        manageCourses.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Manage_CoursesActionPerformed

    private void Manage_CoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Manage_CoursesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Manage_CoursesMouseClicked

    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed
        int response = JOptionPane.showConfirmDialog(
                this,
                "you sure want to logout?",
                "Confirm Logout",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (response == JOptionPane.YES_OPTION) {
            LoginInterface login = new LoginInterface();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logout1ActionPerformed

    private void logout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logout1MouseClicked

    private void Add_New_Management_RolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_New_Management_RolesActionPerformed
        AddManagementRole addManagementRole = new AddManagementRole(Id);
        addManagementRole.setLocationRelativeTo(null);
        addManagementRole.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Add_New_Management_RolesActionPerformed

    private void Add_New_Management_RolesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_New_Management_RolesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_New_Management_RolesMouseClicked

    private void Add_New_Assistant_LecturersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_New_Assistant_LecturersActionPerformed
        AddAssistantLecturer addAssistantLecturer = new AddAssistantLecturer(Id);
        addAssistantLecturer.setLocationRelativeTo(null);
        addAssistantLecturer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Add_New_Assistant_LecturersActionPerformed

    private void Add_New_Assistant_LecturersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_New_Assistant_LecturersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_New_Assistant_LecturersMouseClicked

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void jobRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobRoleActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_nameActionPerformed

    private void manage_StudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_StudentsActionPerformed
        ManageStudents manageStudents = new ManageStudents(Id);
        manageStudents.setLocationRelativeTo(null);
        manageStudents.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manage_StudentsActionPerformed

    private void manage_StudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manage_StudentsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_manage_StudentsMouseClicked

    private void Manage_LecturersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_LecturersActionPerformed
        ManageLecturers manageLecturers = new ManageLecturers(Id);
        manageLecturers.setLocationRelativeTo(null);
        manageLecturers.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Manage_LecturersActionPerformed

    private void Manage_LecturersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Manage_LecturersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Manage_LecturersMouseClicked

    private void Add_New_StudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_New_StudentsActionPerformed
        AddStudent addStudent = new AddStudent(Id);
        addStudent.setLocationRelativeTo(null);
        addStudent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Add_New_StudentsActionPerformed

    private void Add_New_StudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_New_StudentsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_New_StudentsMouseClicked

    private void View_DepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_DepartmentsActionPerformed
        ViewDepartments viewDepartments = new ViewDepartments(Id);
        viewDepartments.setLocationRelativeTo(null);
        viewDepartments.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_View_DepartmentsActionPerformed

    private void View_DepartmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_View_DepartmentsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_View_DepartmentsMouseClicked

    private void Manage_Management_RolesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Manage_Management_RolesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Manage_Management_RolesMouseClicked

    private void Manage_Management_RolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_Management_RolesActionPerformed
        ManageManagementRoles manageManegementRoles = new ManageManagementRoles(Id);
        manageManegementRoles.setLocationRelativeTo(null);
        manageManegementRoles.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Manage_Management_RolesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagementDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagementDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagementDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagementDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagementDashboard("1234").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_New_Assistant_Lecturers;
    private javax.swing.JButton Add_New_Lecturer;
    private javax.swing.JButton Add_New_Management_Roles;
    private javax.swing.JButton Add_New_Students;
    private javax.swing.JButton Manage_Assistant_Lecturers;
    private javax.swing.JButton Manage_Courses;
    private javax.swing.JButton Manage_Lecturers;
    private javax.swing.JButton Manage_Management_Roles;
    private javax.swing.JButton View_Departments;
    private javax.swing.JTextField department;
    private javax.swing.JTextField email;
    private javax.swing.JLabel headerText;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField jobRole;
    private javax.swing.JButton logout1;
    private javax.swing.JButton manage_Students;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables

    private void loadManagementProfile(String Id) {
        try {
            Connection conn = DBManager.getConnection();

            String query = "SELECT m.Employee_Id, m.Name, m.Job_Role, m.Email, ad.Name AS DepartmentName "
                    + "FROM Management m "
                    + "JOIN Management_Department md ON m.Employee_Id = md.Employee_Id "
                    + "JOIN Academic_Department ad ON md.Department_Id = ad.Id "
                    + "WHERE m.Employee_Id = ?";

            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, Id);

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                id.setText(rs.getString("Employee_Id"));
                name.setText(rs.getString("Name"));
                jobRole.setText(rs.getString("Job_Role"));
                email.setText(rs.getString("Email"));
                department.setText(rs.getString("DepartmentName"));
            } else {
                JOptionPane.showMessageDialog(this, "Management employee not found!");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading management profile: " + e.getMessage());
            e.printStackTrace();
        }
    }

}
